version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: flink-fingerprint-main-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
    ports:
      - "2182:2182"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: flink-fingerprint-main-kafka
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jobmanager:
    build: .
    container_name: flink-fingerprint-main-jobmanager
    command: jobmanager
    ports:
      - "18081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        execution.checkpointing.interval: 60000
    volumes:
      - ./src:/opt/flink/jobs/src
      - ./main.py:/opt/flink/jobs/main.py
      - ./output:/opt/flink/output
    depends_on:
      - kafka

  taskmanager:
    build: .
    container_name: flink-fingerprint-main-taskmanager
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    volumes:
      - ./src:/opt/flink/jobs/src
      - ./main.py:/opt/flink/jobs/main.py
      - ./output:/opt/flink/output
